//
// Created by Dan.Alexander on 11/16/2015.
//

#ifndef TILEDJSON_TILEDJSONCONSTS_HPP_HPP
#define TILEDJSON_TILEDJSONCONSTS_HPP_HPP

#define TILEDJSON_NAMESPACE tiledjson

#endif //TILEDJSON_TILEDJSONCONSTS_HPP_HPP
